{
 "title": "Docker monitoring (v0.5)",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "Containers" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(container_cpu_user_seconds_total, source)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{source=~\"$source\"}, namespace)"
   },
   {
    "name": "instance",
    "label": "Node",
    "query": "label_values(container_cpu_user_seconds_total{source=\"$source\", namespace=\"$namespace\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\", source=\"$source\", namespace=\"$namespace\", instance=~\"$instance\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\", source=\"$source\", namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"\", source=\"$source\", namespace=\"$namespace\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\", source=\"$source\", namespace=\"$namespace\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}