{
 "title": "Fluentd (v0.2)",
 "description": "A quick dashboard for displaying Fluentd metrics.",
 "tags": [ "Fluent" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "buffer queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_queue_length"
    }
   ]
  },
  {
   "title": "buffer total queued size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_total_bytes"
    }
   ]
  },
  {
   "title": "retry count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_retry_count{type=\"elasticsearch\"})"
    }
   ]
  },
  {
   "title": "write count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_write_count{type=\"elasticsearch\"}",
     "legendFormat": "output_elasticsearch"
    }
   ]
  }
 ]
}