{
 "title": "Host Stats (v0.6)",
 "tags": [ "Nodes" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(node_boot_time_seconds, source)"
   },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(node_boot_time_seconds{source=\"$source\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}",
     "prometheusLink": "https://admin.prometheus.{{rancher_dns_subdomain_fqdn}}/graph#%5B%7B%22expr%22%3A%22node_load1%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222016-1-19%2020%3A15%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Node Procs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_procs_blocked{instance=~\"$node\"}",
     "legendFormat": "Blocked - {{instance}}",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22sum(rate(node_cpu_seconds_total%7Binstance%3D%5C%2210.196.94.38%3A9100%5C%22%2Cmode!%3D%5C%22idle%5C%22%7D%5B1m%5D)%20*%20100)%20by%20(node_cpu)%20%2F8%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222016-1-16%207%3A10%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "expr": "node_procs_running{instance=~\"$node\"}",
     "legendFormat": "Running - {{instance}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22node_memory_MemAvailable_bytes%7Binstance%3D%5C%2210.196.94.100%3A9100%5C%22%7D%20%2F%201048576%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222016-1-16%207%3A11%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Committed Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Committed_AS_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22node_memory_Committed_AS_bytes%7Binstance%3D%5C%2210.196.94.38%3A9100%5C%22%7D%20%2F%201048576%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222016-1-16%207%3A13%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Memory Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 17 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemFree_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 17 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Node Disk Read Time",
   "type": "graph",
   "description": "The total number of milliseconds spent by all reads.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(node_disk_read_time_seconds_total{source=\"$source\", instance=~\"$node\"}[90s])) by (instance)",
     "legendFormat": "{{instance}}",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22rate(node_disk_read_time_seconds_total%7Binstance%3D%5C%2210.196.94.100%3A9100%5C%22%2Cdevice!%3D%5C%22sr0%5C%22%7D%5B30s%5D)%22%2C%22range_input%22%3A%2286400s%22%2C%22end_input%22%3A%222016-1-7%2014%3A58%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Used Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "percentunit", "label": "Disk usage %" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$node\"} - node_filesystem_free_bytes{instance=~\"$node\"}) / node_filesystem_size_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}} - {{fstype}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{device=\"eth0\", instance=~\"$node\"}[5m])",
     "legendFormat": "Eth0 Receive Drops {{instance}}"
    }
   ]
  }
 ]
}