{
 "title": "Kubernetes Capacity (v1.1)",
 "description": "Kubernetes Capacity",
 "tags": [ "Kubernetes" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(kube_pod_info, source)"
   }
  ]
 },
 "panels": [
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\", source=~\"$source\"}[2m])) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{source=~\"$source\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "sum(node_load5{source=~\"$source\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "sum(node_load15{source=~\"$source\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{source=~\"$source\"}) - sum(node_memory_MemFree_bytes{source=~\"$source\"}) - sum(node_memory_Buffers_bytes{source=~\"$source\"}) - sum(node_memory_Cached_bytes{source=~\"$source\"})",
     "legendFormat": "memory usage"
    },
    {
     "expr": "sum(node_memory_Buffers_bytes{source=~\"$source\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{source=~\"$source\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{source=~\"$source\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes{source=~\"$source\"}) - sum(node_memory_MemFree_bytes{source=~\"$source\"}) - sum(node_memory_Buffers_bytes{source=~\"$source\"}) - sum(node_memory_Cached_bytes{source=~\"$source\"})) / sum(node_memory_MemTotal_bytes{source=~\"$source\"})) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{source=~\"$source\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{source=~\"$source\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{source=~\"$source\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\", source=\"$source\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\", source=\"$source\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\", source=\"$source\"}) * 100"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\", source=\"$source\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\", source=\"$source\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_info{source=\"$source\"})",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{source=\"$source\"})",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods{source=\"$source\"}) - sum(kube_pod_info{source=\"$source\"})) / sum(kube_node_status_capacity_pods{source=\"$source\"}) * 100"
    }
   ]
  }
 ]
}