{
 "title": "NodeJS (v0.2)",
 "tags": [ "Nodejs" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Instances count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"nodejs-example\",namespace=\"dev\"})"
    }
   ]
  },
  {
   "title": "Nodejs Hit DEV",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(tot_request_example{kubernetes_namespace=\"dev\"})"
    }
   ]
  },
  {
   "title": "Hit by namespaces",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tot_request_example" }
   ]
  }
 ]
}